# sys-scan Intelligence Layer configuration
# All keys optional; defaults shown. Commit for reproducible enrichment behavior.

weights:
  # Risk weighting factors (can also override via env: AGENT_WEIGHT_IMPACT, etc.)
  impact: 1.0
  exposure: 1.0
  anomaly: 1.0

thresholds:
  # If summed risk_total (or fallback risk_score) of MEDIUM+ findings is below this AND there are no baseline:new findings => skip LLM/executive summarization stage
  summarization_risk_sum: 150
  # Cosine (or configured) distance threshold for process novelty clustering
  process_novelty_distance: 0.35
  # Absolute Z-score threshold beyond which metric drift synthetic findings are emitted
  metric_drift_z: 2.5

performance:
  # Enable parallel feature vector computation for novelty analysis (False favors determinism under legacy interpreters)
  parallel_baseline: true
  # Worker threads (CPU bound but lightweight hashing / parsing)
  workers: 4

paths:
  # Additional rule directories (loaded & cached with mtime checks).
  # Example: ["rules/custom", "rules/experimental" ]
  rule_dirs: []
  # Additional executable allowlist paths merged with file + env sources (policy_allowlist.yaml + AGENT_POLICY_ALLOWLIST)
  policy_allowlist: []

notifications:
  # Slack incoming webhook URL (leave null to disable). Example: https://hooks.slack.com/services/T000/B000/XXXXX
  slack_webhook: null
  # Generic alternative webhook (POST JSON: {"text": "..."}) used if slack_webhook unset
  webhook: null
  # Trigger notification if avg probability_actionable delta >= threshold OR any new HIGH+ baseline:new finding
  actionable_delta_threshold: 0.15

reports:
  # Generate static HTML artifact (no external JS). Disable to reduce CI artifact volume.
  html_enabled: true
  html_path: enriched_report.html
  diff_markdown_path: enriched_diff.md

bundle:
  # Manifest file capturing version, rule pack SHA, embedding model hash, and weights snapshot
  manifest_path: manifest.json
