module;

#include <coroutine>
#include <vector>
#include <string>
#include <thread>
#include <chrono>
#include <variant>
#include <iostream>
#include <array>
#include <cstring>
#include <algorithm>
#include <iterator>
#include <cctype>

// Platform specific headers must be in global fragment
#ifdef SYS_SCAN_HAVE_EBPF
#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include <arpa/inet.h>
// The skeleton header is generated by CMake at build time
#include "process_exec.skel.h"
#endif

export module sys_scan.scanners.ebpf;

import sys_scan.types;
import sys_scan.scanner;
import sys_scan.coro;
import sys_scan.interfaces;
import sys_scan.config;
import sys_scan.utils;

export namespace sys_scan {

// Binary-compatible structs for BPF ring buffer
// Using std::array ensures safety while keeping memory layout identical to C
struct ExecEvent {
    uint32_t type;
    uint32_t pid;
    std::array<char, 16> comm;
};

struct ConnEvent {
    uint32_t type;
    uint32_t pid;
    uint32_t daddr;
    uint16_t dport;
    std::array<char, 16> comm;
    uint8_t is_ipv6;
    std::array<uint32_t, 4> daddr6;
};

class EbpfScanner : public Scanner {
    const IFileSystem& fs_;
    const Config& config_;
    const ISleeper& sleeper_;

public:
    explicit EbpfScanner(const Config& cfg, const IFileSystem& fs, const ISleeper& sleeper)
        : config_(cfg), fs_(fs), sleeper_(sleeper) {}

    std::string name() const override { return "ebpf_trace"; }
    std::string description() const override { return "Trace execve/connect via eBPF (with /proc fallback)"; }

    Generator<Finding> scan() override {
#ifdef SYS_SCAN_HAVE_EBPF
        if (config_.ioc_exec_trace) {
            // 1. Attempt eBPF Trace
            auto bpf_results = run_bpf_trace();
            if (bpf_results.empty()) {
                // 2. Fallback if BPF failed to load/attach
                co_yield Finding{
                    .id = "ebpf_fallback",
                    .title = "eBPF Trace Failed",
                    .severity = Severity::Info,
                    .description = "Falling back to /proc polling"
                };
                // Delegate to fallback generator
                for (auto f : run_proc_fallback()) co_yield f;
            } else {
                for (const auto& f : bpf_results) co_yield f;
            }
        } else {
            co_return;
        }
#else
        // No eBPF support compiled in
        for (auto f : run_proc_fallback()) co_yield f;
#endif
    }

private:
    // --- /proc Fallback Implementation ---
    std::vector<Finding> run_proc_fallback() {
        std::vector<Finding> findings;

        const std::string proc_root = sys_scan::utils::in_root(config_.test_root, "/proc");
        // Simple snapshot difference logic
        auto get_pids = [&]() {
            std::vector<std::string> pids;
            auto entries = fs_.list_directory(proc_root);
            for (const auto& e : entries) {
                if (e.is_directory && std::all_of(e.name.begin(), e.name.end(), ::isdigit))
                    pids.push_back(e.name);
            }
            std::sort(pids.begin(), pids.end());
            return pids;
        };

        auto pids_start = get_pids();
        // Sleep to catch short lived processes (imperfect, hence fallback)
        sleeper_.sleep_for(std::chrono::milliseconds(1000LL * (config_.ioc_exec_trace_seconds > 0 ? config_.ioc_exec_trace_seconds : 2)));
        auto pids_end = get_pids();

        std::vector<std::string> new_pids;
        std::set_difference(pids_end.begin(), pids_end.end(),
                            pids_start.begin(), pids_start.end(),
                            std::back_inserter(new_pids));

        for (const auto& pid : new_pids) {
            std::string comm = fs_.read_file(proc_root + "/" + pid + "/comm");
            if (!comm.empty() && comm.back() == '\n') comm.pop_back();

            Finding f;
            f.id = "proc_exec:" + pid;
            f.title = "Process Started (Fallback)";
            f.description = "Process " + pid + " (" + comm + ") detected via polling";
            f.metadata["pid"] = pid;
            f.metadata["comm"] = comm;
            f.metadata["method"] = "proc_poll";
            findings.push_back(f);
        }
        return findings;
    }

#ifdef SYS_SCAN_HAVE_EBPF
    // --- eBPF Implementation ---
    static int handle_event(void* ctx, void* data, size_t len) {
        auto* results = static_cast<std::vector<Finding>*>(ctx);

        if (len == sizeof(ExecEvent)) {
            auto* e = static_cast<ExecEvent*>(data);
            auto comm_len = strnlen(e->comm.data(), e->comm.size());
            std::string comm{e->comm.data(), comm_len};

            Finding f;
            f.id = "bpf_exec:" + std::to_string(e->pid);
            f.title = "Process Execution";
            f.description = "Execve detected: " + comm;
            f.metadata["pid"] = std::to_string(e->pid);
            f.metadata["comm"] = comm;
            f.metadata["method"] = "ebpf";
            results->push_back(f);
        }
        else if (len == sizeof(ConnEvent)) {
            auto* c = static_cast<ConnEvent*>(data);
            char ip[INET6_ADDRSTRLEN];
            if (c->is_ipv6)
                inet_ntop(AF_INET6, c->daddr6.data(), ip, sizeof(ip));
            else
                inet_ntop(AF_INET, &c->daddr, ip, sizeof(ip));

            Finding f;
            f.id = "bpf_net:" + std::to_string(c->pid);
            f.title = "Outbound Connection";
            f.description = "Connect to " + std::string(ip) + ":" + std::to_string(ntohs(c->dport));
            f.metadata["pid"] = std::to_string(c->pid);
            f.metadata["dst_ip"] = ip;
            results->push_back(f);
        }
        return 0;
    }

    std::vector<Finding> run_bpf_trace() {
        std::vector<Finding> results;
        struct process_exec_bpf* skel = process_exec_bpf__open();
        if (!skel) return results;

        if (process_exec_bpf__load(skel)) {
            process_exec_bpf__destroy(skel);
            return results;
        }

        if (process_exec_bpf__attach(skel)) {
            process_exec_bpf__destroy(skel);
            return results;
        }

        struct ring_buffer* rb = ring_buffer__new(bpf_map__fd(skel->maps.events), handle_event, &results, nullptr);
        if (!rb) {
            process_exec_bpf__destroy(skel);
            return results;
        }

        // Poll for specified duration
        int duration = config_.ioc_exec_trace_seconds > 0 ? config_.ioc_exec_trace_seconds : 3;
        auto start = std::chrono::steady_clock::now();
        while (std::chrono::steady_clock::now() - start < std::chrono::seconds(duration)) {
            ring_buffer__poll(rb, 100 /* ms */);
        }

        ring_buffer__free(rb);
        process_exec_bpf__destroy(skel);
        return results;
    }
#endif
};

}